import { Inter } from "next/font/google";
import "./globals.css";
import Toppart from "./parts/toppart";
import Part1 from "./parts/mainhead";
import Navi from "./parts/navbar";
import Mobnav from "./parts/mobilenav";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "./parts/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <Toppart/>
      <Part1/>
      <Navi/>
      <Mobnav/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
